# Copyright 2014-2018 CERN for the benefit of the ATLAS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - Thomas Beermann, <thomas.beermann@cern.ch>, 2018

version: "2"
services:
  ubuntu:
    image: ubuntu
    container_name: ubuntu
    tty: true
    networks:
      - rucionetwork
    extra_hosts:
      - "rucio-db:172.24.0.9"
      - "rucio-db-streamer:172.24.0.7"
      - "rucio-server:172.24.0.3"

  rucio-client:
      build:
        context: ./rucio-client-custom-branch
        dockerfile: Dockerfile
      image: slidspitfire/rucio-client-custom-branch:latest
      container_name: rucio-client
      hostname: rucio-client
      depends_on:
        - "rucio-server"
        - "rucio-db-pool"
      volumes:
        - /tmp/fts-voms-proxy:/tmp/fts-voms-proxy
      networks:
        - rucionetwork
      tty: true
      
  rucio-ui:
    build:
      context: ./rucio-ui
      dockerfile: Dockerfile
    image: slidspitfire/rucio-ui:latest
    container_name: rucio-ui
    hostname: rucio-ui
    ports:
      - "443:443"
    depends_on:
      - "rucio-db-pool"
    networks:
      - rucionetwork
    command: ["httpd", "-D", "FOREGROUND"]

  rucio-server:
    build:
      context: ./rucio-server-custom-branch
      dockerfile: Dockerfile
    image: slidspitfire/rucio-server-custom-branch:latest
    container_name: rucio-server
    hostname: rucio-server
    ports:
      - "9443:443"
    networks:
      - rucionetwork
    extra_hosts:
      - "rucio-db-pool:172.24.0.17"
    volumes:
      - /tmp/fts-voms-proxy:/tmp/fts-voms-proxy
    depends_on:
      - "rucio-db-pool"
      - "rucio-fts-proxy-delegator"
    command: ["httpd", "-D", "FOREGROUND"]

  rucio-fts-proxy-delegator:
    build:
      context: ./rucio-fts-proxy-delegator
      dockerfile: Dockerfile
    image: slidspitfire/rucio-fts-proxy-delegator:latest
    container_name: rucio-fts-proxy-delegator
    hostname: rucio-fts-proxy-delegator
    networks:
      - rucionetwork
    volumes:
      - ~/.globus:/root/.globus
      - /tmp/fts-voms-proxy:/tmp/fts-voms-proxy
    tty: true

  # rucio-db-pool:
  #   build:
  #     context: ./rucio-pgpool
  #     dockerfile: Dockerfile
  #   image: slidspitfire/rucio-db-pool:latest
  #   container_name: rucio-db-pool
  #   hostname: rucio-db-pool
  #   ports:
  #     - "5432:5433"
  #   networks:
  #     rucionetwork:
  #       ipv4_address: 172.24.0.17
  #   extra_hosts:
  #     - "rucio-db:172.24.0.9"
  #     - "rucio-db-streamer:172.24.0.7"
  #     - "rucio-server:172.24.0.3"
  #   depends_on:
  #     - "rucio-db-master"
  #     - "rucio-db-streamer"

  # rucio-db-master:
  #   build:
  #     context: ./rucio-db-master
  #     dockerfile: Dockerfile
  #   image: slidspitfire/rucio-db-master:latest
  #   container_name: rucio-db-master
  #   hostname: rucio-db-master
  #   # ports:
  #   #   - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=pippo123
  #   networks:
  #     rucionetwork:
  #       ipv4_address: 172.24.0.9
  #   extra_hosts:
  #     - "rucio-db-pool:172.24.0.17"

  # rucio-db-mysql:
  #   image: mysql:5.7
  #   container_name: rucio-db-mysql
  #   hostname: rucio-db-mysql
  #   environment:
  #     - MYSQL_USER=rucio
  #     - MYSQL_PASSWORD=pippo123
  #     - MYSQL_DATABASE=rucio
  #     - MYSQL_ROOT_PASSWORD=pippo123
  #   networks:
  #     rucionetwork:
  #       ipv4_address: 172.24.0.77
  #   tty: true

  # rucio-db-streamer:
  #   build:
  #     context: ./rucio-db-master
  #     dockerfile: Dockerfile
  #   image: slidspitfire/rucio-db-master:latest
  #   container_name: rucio-db-streamer
  #   hostname: rucio-db-streamer
  #   # ports:
  #   #   - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=pippo123
  #   networks:
  #     rucionetwork:
  #       ipv4_address: 172.24.0.7
  #   extra_hosts:
  #     - "rucio-db-slave:172.24.0.8"
  #     - "rucio-db-pool:172.24.0.17"

  # rucio-db-slave:
  #   build:
  #     context: ./rucio-db-slave
  #     dockerfile: Dockerfile
  #   image: slidspitfire/rucio-db-slave:latest
  #   container_name: rucio-db-slave
  #   hostname: rucio-db-slave
  #   # ports:
  #   #   - "54320:5432"
  #   networks:
  #     rucionetwork:
  #       ipv4_address: 172.24.0.8
  #   extra_hosts:
  #     - "rucio-db-streamer:172.24.0.7"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=pippo123


  rucio-roach1:
    container_name: rucio-roach1
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      roachnet:
        aliases:
          - rucio-roach1
      rucionetwork:
        aliases:
          - rucio-roach1

  rucio-roach2:
    container_name: rucio-roach2
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure --join=rucio-roach1
    depends_on:
      - rucio-roach1
    networks:
      roachnet:
        aliases:
          - rucio-roach2
      rucionetwork:
        aliases:
          - rucio-roach2

  rucio-roach3:
    container_name: rucio-roach3
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure --join=rucio-roach1
    depends_on:
      - rucio-roach1
    networks:
      roachnet:
        aliases:
          - rucio-roach3
      rucionetwork:
        aliases:
          - rucio-roach3

networks:
  rucionetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1
  roachnet:
    driver: bridge
    ipam:
      config:
        - subnet: 173.24.0.0/16
          gateway: 173.24.0.1